FORMAT: 1A
HOST: http://www.kreuzwerker.de

# World Cup API
The **World Cup API** lets you manage World Cup games.


# Game [/games/{id}]
A single world cup game.

+ Model

    + Body
    
            {
                "id": 2, 
                "home": "Mexico",
                "guest": "Cameroon",
                "location": "Natal"
            }
            
+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the game.

# Retrieve a Game [GET]
+ Response 200 (application/json)
        
    [Game][]

+ Response 404
